
package com.nwpu.todoservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TodoService", targetNamespace = "http://www.todoservice.nwpu.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodoService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.LoginResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/loginRequest", output = "http://www.todoservice.nwpu.com/TodoService/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTodo", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.AddTodo")
    @ResponseWrapper(localName = "addTodoResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.AddTodoResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/addTodoRequest", output = "http://www.todoservice.nwpu.com/TodoService/addTodoResponse")
    public String addTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.nwpu.todoservice.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUser", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.FindUser")
    @ResponseWrapper(localName = "findUserResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.FindUserResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/findUserRequest", output = "http://www.todoservice.nwpu.com/TodoService/findUserResponse")
    public User findUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkTodo", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.CheckTodo")
    @ResponseWrapper(localName = "checkTodoResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.CheckTodoResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/checkTodoRequest", output = "http://www.todoservice.nwpu.com/TodoService/checkTodoResponse")
    public String checkTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTodo", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.DeleteTodo")
    @ResponseWrapper(localName = "deleteTodoResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.DeleteTodoResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/deleteTodoRequest", output = "http://www.todoservice.nwpu.com/TodoService/deleteTodoResponse")
    public String deleteTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearTodo", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.ClearTodo")
    @ResponseWrapper(localName = "clearTodoResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.ClearTodoResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/clearTodoRequest", output = "http://www.todoservice.nwpu.com/TodoService/clearTodoResponse")
    public String clearTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.todoservice.nwpu.com", className = "com.nwpu.todoservice.RegisterResponse")
    @Action(input = "http://www.todoservice.nwpu.com/TodoService/registerRequest", output = "http://www.todoservice.nwpu.com/TodoService/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
